"""Isaac Lab ArticulationCfg for the MentorPi robots.

Two configs:
  MENTORPI_CFG         base only (mecanum + camera + lidar)
  MENTORPI_SO101_CFG   full mobile manipulator (+ SO-101 arm)

Joint names, limits, and the init pose below are taken verbatim from the
calibrated URDF (isaac/*.isaac.urdf, generated by isaac/export_isaac.sh from
mecanum.xacro). If calibration changes, re-export and re-convert to USD; the
joint NAMES are stable, so this file rarely needs edits.

VERSION NOTE: written against the current `isaaclab.*` API. On older Isaac Lab
(Orbit) replace `isaaclab` with `omni.isaac.lab`. Adjust `usd_path` to wherever
you saved the URDF->USD conversion (see isaac/README.md).

MECANUM CAVEAT: Isaac does not simulate mecanum rollers. These configs drive the
4 wheels as plain revolute joints (velocity control). For holonomic motion you
must map (vx, vy, wz) -> per-wheel speeds yourself and/or model the rollers;
spinning all four wheels forward only yields longitudinal motion here.
"""

from __future__ import annotations

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

# Absolute path is fine for a single machine; point this at your converted USD.
# Produce the USDs with the Isaac Sim URDF Importer (GUI) or Isaac Lab's
# scripts/tools/convert_urdf.py — see isaac/README.md.
_USD_DIR = "/media/luo/Game/data/code/MentorPi/isaac/usd"

# SO-101 arm joints (revolute, effort/velocity limits = 10 from the URDF).
_ARM_JOINTS = [
    "so101_shoulder_pan",
    "so101_shoulder_lift",
    "so101_elbow_flex",
    "so101_wrist_flex",
    "so101_wrist_roll",
    "so101_gripper",
]

_COMMON_SPAWN = dict(
    activate_contact_sensors=False,
    rigid_props=sim_utils.RigidBodyPropertiesCfg(
        disable_gravity=False,
        max_depenetration_velocity=5.0,
    ),
    articulation_props=sim_utils.ArticulationRootPropertiesCfg(
        enabled_self_collisions=False,
        solver_position_iteration_count=8,
        solver_velocity_iteration_count=1,
    ),
)

# Wheels: velocity-controlled -> stiffness 0, damping provides the drive.
_WHEEL_ACTUATOR = ImplicitActuatorCfg(
    joint_names_expr=["wheel_.*_Joint"],
    effort_limit=5.0,
    velocity_limit=30.0,   # rad/s; ~1 m/s at r=0.0318 m
    stiffness=0.0,
    damping=2.0,
)

# base_footprint is a massless frame link; on import (merge fixed joints) it
# collapses into base_link, which becomes the free-floating articulation root.

MENTORPI_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(usd_path=f"{_USD_DIR}/mentorpi.usd", **_COMMON_SPAWN),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.05),   # base_link ~5 cm above ground
        joint_pos={"wheel_.*_Joint": 0.0},
        joint_vel={".*": 0.0},
    ),
    actuators={"wheels": _WHEEL_ACTUATOR},
)

MENTORPI_SO101_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=f"{_USD_DIR}/mentorpi_so101.usd", **_COMMON_SPAWN
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.05),
        joint_pos={
            "wheel_.*_Joint": 0.0,
            # Arm home = all zeros (within URDF limits). Set a folded transport
            # pose here if you prefer.
            **{j: 0.0 for j in _ARM_JOINTS},
        },
        joint_vel={".*": 0.0},
    ),
    actuators={
        "wheels": _WHEEL_ACTUATOR,
        "arm": ImplicitActuatorCfg(
            joint_names_expr=["so101_.*"],
            effort_limit=10.0,       # matches URDF <limit effort="10">
            velocity_limit=10.0,     # matches URDF <limit velocity="10">
            stiffness=40.0,          # position control; tune per task
            damping=4.0,
        ),
    },
)
